Repository jav1palace/nonamekitchen, pull requests merged in 2022-09, with the labels that each got.

#1 NNK-1 Fix the type back to string
  src/app.service.ts
Labels: bug

#3 NNK-2 Add dependabot to keep up with `npm` dependencies
  .github/dependabot.yml
Labels: security

#10 Changes to fix deployment
  src/app.module.ts
  src/main.ts
Labels: bug

#11 Change database secrets
  .env.development
Labels: bug

#12 Fix DB in Heroku
  .env.development
  .env.production
Labels: bug

#19 Users & Encryption modules
  .husky/pre-commit
  package-lock.json
  package.json
  src/app.module.ts
  src/database/database.module.ts
  src/encryption/encryption.module.ts
  src/encryption/encryption.service.spec.ts
  src/encryption/encryption.service.ts
  src/login/dto/login.dto.ts
  src/login/login.controller.spec.ts
  src/login/login.controller.ts
  src/login/login.module.ts
  src/login/login.service.spec.ts
  src/login/login.service.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/login.e2e-spec.ts
  test/users.e2e-spec.ts
Labels: feature

#20 Update port for heroku db
  .env.production
  .github/workflows/deploy.yml
Labels: bug

#21 Typo
  .github/workflows/deploy.yml
Labels: bug

#25 Add authentication for selected endpoints
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/constants.ts
  src/auth/dto/auth.dto.ts
  src/auth/guards/jwt-auth.guard.ts
  src/auth/guards/local-auth.guard.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/database/database.module.ts
  src/encryption/encryption.service.ts
  src/login/dto/login.dto.ts
  src/login/login.controller.ts
  src/login/login.module.ts
  src/login/login.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  test/auth.e2e-spec.ts
  test/users.e2e-spec.ts
Labels: feature

#32 Add authorization for e2e tests and make them realistic
  test/users.e2e-spec.ts
Labels: enhancement
